[book]
authors = ["Rick Weber", "Ravital Solomon", "Sam Tay"]
language = "en"
multilingual = false
src = "src"
title = "Sunscreen Documentation"

[output.html]
mathjax-support = true

[output.html.fold]
enable = true

[rust]
edition = "2021"
