name: "Playground production deployment"

on: 
  workflow_dispatch:
    inputs:
      deployment_id:
        description: 'The ID of a preproduction playground deployment version to deploy to production'
        required: true

concurrency: playground-production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy
      run: aws elasticbeanstalk update-environment --application-name Playground --environment-id $ENVIRONMENT_ID --description "Deployment for ID ${{ github.event.inputs.deployment_id}}" --version-label ${{ github.event.inputs.deployment_id}}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYMENT_AWS_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-west-2
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYMENT_AWS_ACCESS_KEY_SECRET }}
        ENVIRONMENT_ID: e-ehgmnmqadu